import StyledComponentsRegistry from "@/lib/registery";
import type { Metadata } from "next";
import { DM_Sans, Sora } from "next/font/google";
import GlobalStyles from "./global-styles";
import { cookies } from "next/headers";
import TabBar from "@/layouts/tab-bar";
import { ToastContainer } from "react-toastify";

const sora = Sora({
    subsets: ["latin"],
});

const dmSans = DM_Sans({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "DKtiv",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    const isConnected = (await cookies()).has("access_token");

    return (
        <html lang="fr">
            <StyledComponentsRegistry>
                <GlobalStyles />
                <body className={`${sora.className} ${dmSans.className}`}>
                    {children}
                    {isConnected && <TabBar />}
                    <ToastContainer />
                </body>
            </StyledComponentsRegistry>
        </html>
    );
}
