import StyledComponentsRegistry from "@/lib/registery";
import type { Metadata } from "next";
import { DM_Sans, Sora } from "next/font/google";
import GlobalStyles from "./global-styles";

const sora = Sora({
    subsets: ["latin"],
});

const dmSans = DM_Sans({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "DKtiv",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="fr">
            <StyledComponentsRegistry>
                <GlobalStyles />
                <body className={`${sora.className} ${dmSans.className}`}>
                    {children}
                </body>
            </StyledComponentsRegistry>
        </html>
    );
}
